language: node_js
node_js:
  - "10"
cache: npm
script: cd client && npm install && npm run build && cd ..
deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key:
      secure: $SECRETACCESSKEY
    region: us-east-1
    app: MultiBeast
    env: multibeast
    bucket_name: elasticbeanstalk-us-east-1-583653169187
    skip_cleanup: true
    zip_file: client/build
    on:
      branch:
        - master
        - production
      repo: aspen-institute/MultiBeast
  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    app: multibeast
    skip_cleanup: true
    on:
      branch: 
        - heroku
        - staging