language: node_js
node_js:
  - "10"
cache: npm
after_install: 
  - cd client && npm install
  - echo "react dependencies installed"
  - npm run build
  - echo "react build complete"
  - cd ..
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: us-east-1
  app: MultiBeast
  env: multibeast
  bucket_name: elasticbeanstalk-us-east-1-583653169187
  on:
    repo: aspen-institute/MultiBeast
